# fly.toml file generated for iankim on 2023-07-24T15:38:19-07:00

app = "arena-backend"
kill_signal = "SIGINT"
kill_timeout = 5
primary_region = "bos"

[env]
  PORT = "8000"

[[services]]
  internal_port = 8080
  protocol = "tcp"
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20

  [[services.ports]]
    handlers = ["http"]
    port = "80"

  [[services.ports]]
    handlers = ["tls", "http"]
    port = "443"

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    port = "8080"
    restart_limit = 6
    timeout = "2s"
